name: Trigger auto deployment for container-app-ckzytst2p2r2o

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-ckzytst2p2r2o-AutoDeployTrigger-49bc6741-bd44-4578-8f7a-a73682242cc0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPCKZYTST2P2R2O_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPCKZYTST2P2R2O_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPCKZYTST2P2R2O_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryckzytst2p2r2o.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPCKZYTST2P2R2O_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPCKZYTST2P2R2O_REGISTRY_PASSWORD }}
          containerAppName: container-app-ckzytst2p2r2o
          resourceGroup: expresshello8dec958d
          imageToBuild: containerregistryckzytst2p2r2o.azurecr.io/container-app-ckzytst2p2r2o:${{ github.sha }}
          


